#git clone https://github.com/thesandlord/mongo-k8s-sidecar.git

- name: Connect to cluster
  shell: gcloud container clusters get-credentials cluster-nodepool --zone us-central1-a --project fintechx-feladat

- name: Setting up MongoDB Storage Class
  shell: |
    cd ./mongo-k8s-sidecar/example/StatefulSet/
    kubectl apply -f googlecloud_ssd.yaml

- name: Deploying the Headless Service and StatefulSet for MongoDB
  shell: |
    cd ./mongo-k8s-sidecar/example/StatefulSet/
    kubectl apply -f mongo-statefulset.yaml

- name: sleep for 30 seconds and continue with play
  wait_for:
    timeout: 30
  delegate_to: localhost

- name: Waiting for the pods
  shell: |
    kubectl get statefulset
    kubectl get pods
  register: statefulset

- name: Print statefulset
  debug:
    var: statefulset.stdout_lines