- name: FintechX-task running
  hosts: localhost
  gather_facts: no

  vars:
    gcp_cred_file: /home/mate/Documents/gcp_ansible/keys/fintechx-feladat-7f3d30b50aab.json
    gcp_project: fintechx-feladat
    gcp_cred_kind: serviceaccount

  tasks:
  - name: create a cluster
    gcp_container_cluster:
      name: cluster-nodepool
      initial_node_count: 1
      location: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: cluster

  - name: create a node pool
    gcp_container_node_pool:
      name: my-pool
      initial_node_count: 2
      cluster: "{{ cluster }}"
      location: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present